---
- name: Abfrage der Running-Config eines Cisco IOS-Routers
  hosts: ios
  gather_facts: no

  tasks:
    - name: Erstelle Loopback-Interface
      ios_interface:
        name: Loopback0  # Name des Loopback-Interfaces
        description: Ansible Loopback Interface
        state: present  # Stellen Sie sicher, dass das Interface vorhanden ist

    - name: Konfiguriere IP-Adresse auf Loopback-Interface
      ios_config:
        lines:
          - interface Loopback0
          - ip address 10.99.99.97 255.255.255.255  # Hier die gewünschte IP-Adresse und Subnetzmaske eintragen
        parents: interface Loopback0 # Führen Sie dies nur auf dem richtigen interface aus

    - name: Konfigurationsabfrage
      ios_command:
        commands:
          - show running-config
      register: config_output

    - name: Anzeige der Konfiguration
      debug:
        var: config_output.stdout_lines[0]

    - name: Konfiguration nach ./backups/ speichern
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "backups/show_run_loopback{{ inventory_hostname }}.txt"